---
title: "Take-home Exercise 2"
author: "Stefanie Felicia"
date: "May, 12 2025"
date-modified: "last-modified"
execute: 
  eval: true
  echo: true
  warning: false
  freeze: true
---

## 1. Background

Over the past decade, the community of Oceanus has undergone transformations and challenges evolving from its fishing-centric origins. (there used to be illegal fishing but now these ppl has shifting on to another investment e.g. ocean tourism industry which makes a growing tension.) with teh growing tourism, it attracted interntaional pop star Sailor Shift (who wanted to shoot his/her new mv in the island).

\
Clepper Jensen is a former analyst at FishEye company who is new a seasoned journalist for Hecklee Herald, is observing the tension and recently looking at temporary closure of Nemo Reef. By using investigative tools and radio communication, he uncovered a complex web of expedited approvals and secretive logistics -\> this reveals story involving high-level Oceanus officials, Sailor Shift's team, local influential families adn local conservationist group (the Green Guardians) - this is a story of corruption and manipulation.

**Your task is to develop new and novel visualizations and visual analytics approaches to help Clepper get to the bottom of this story.**

### 1.2 Objective 

Objective of this exercise:

Clepper diligently recorded all intercepted radio communications over the last two weeks. With the help of his intern, they have analyzed their content to identify important events and relationships between key players. The result is a knowledge graph describing the last two weeks on Oceanus. Clepper and his intern have spent a large amount of time generating this knowledge graph, and they would now like some assistance using it to answer the following questions.

1.  Clepper found that messages frequently came in at around the same time each day.

    1.  Develop a graph-based visual analytics approach to identify any daily temporal patterns in communications.

    2.  How do these patterns shift over the two weeks of observations?

    3.  Focus on a specific entity and use this information to determine who has influence over them.

2.  Clepper has noticed that people often communicate with (or about) the same people or vessels, and that grouping them together may help with the investigation.

    1.  Use visual analytics to help Clepper understand and explore the interactions and relationships between vessels and people in the knowledge graph.

    2.  Are there groups that are more closely associated? If so, what are the topic areas that are predominant for each group?

        -   For example, these groupings could be related to: Environmentalism (known associates of Green Guardians), Sailor Shift, and fishing/leisure vessels.

3.  It was noted by Clepper’s intern that some people and vessels are using pseudonyms to communicate.

    1.  Expanding upon your prior visual analytics, determine who is using pseudonyms to communicate, and what these pseudonyms are

        -   Some that Clepper has already identified include: “Boss”, and “The Lookout”, but there appear to be many more.

        -   To complicate the matter, pseudonyms may be used by multiple people or vessels.

    2.  Describe how your visualizations make it easier for Clepper to identify common entities in the knowledge graph

    3.  How does your understanding of activities change given your understanding of pseudonyms

4.  Clepper suspects that Nadia Conti, who was formerly entangled in an illegal fishing scheme, may have continued illicit activity within Oceanus.

    1.  Through visual analytics, provide evidence that Nadia is, or is not, doing something illegal

    2.  Summarize Nadia’s actions visually. Are Clepper’s suspicions justified?

### 1.3 The Data

### 1.4 Load Required Libraries

### 1.5 Import Data

how many variable (details of the dataset)
